### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by mindplay-dk** [erusev/parsedown-extra#69]
I discovered an edge case that generates an exception.

```
#0 C:\workspace\test\php-markdown-test\vendor\erusev\parsedown-extra\ParsedownExtra.php(473): {closure}(8, 'Trying to get p...', 'C:\\workspace\\te...', 473, Array)
#1 C:\workspace\test\php-markdown-test\vendor\erusev\parsedown-extra\ParsedownExtra.php(228): ParsedownExtra->processTag('<>')
#2 C:\workspace\test\php-markdown-test\vendor\erusev\parsedown\Parsedown.php(258): ParsedownExtra->blockMarkupComplete(Array)
#3 C:\workspace\test\php-markdown-test\vendor\erusev\parsedown\Parsedown.php(39): Parsedown->lines(Array)
#4 C:\workspace\test\php-markdown-test\vendor\erusev\parsedown-extra\ParsedownExtra.php(46): Parsedown->text('<>\r\n')
```

**Comment by erusev** [comment]
can u reproduce it at the website http://parsedown.org/extra/

**Comment by cebe** [comment]
@erusev if you enter `<>` followed by a new line, this also happens on the website:

```
 Fatal error: Call to a member function getAttribute() on a non-object in /var/www/parsedown.org/shared/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 477
```

**Comment by janschoenherr** [comment]
The same happens for `<body>a</body>`
